const { GoogleGenerativeAI } = require('@google/generative-ai');

/**
 * Generate an image using the Gemini 2.5 Flash Image model
 * @param {string} prompt - The text prompt for image generation
 * @returns {Promise<Buffer>} - Image buffer
 */
const generateImageWithBnana = async (prompt) => {
    try {
        const apiKey = process.env.GEMINI_API_KEY;

        if (!apiKey) {
            throw new Error('GEMINI_API_KEY is not configured in environment variables');
        }

        console.log('🤖 Calling Gemini 2.5 Flash Image API...');

        // Initialize the Gemini API
        const genAI = new GoogleGenerativeAI(apiKey);

        // Get the Gemini 2.5 Flash Image model
        const model = genAI.getGenerativeModel({
            model: 'gemini-2.5-flash-image'
        });

        // Generate image from text prompt
        const result = await model.generateContent({
            contents: [{
                role: 'user',
                parts: [{
                    text: prompt
                }]
            }],
            generationConfig: {
                temperature: 0.7,
                topK: 40,
                topP: 0.95,
                maxOutputTokens: 8192,
            }
        });

        const response = result.response;

        // Check if the response contains an image
        if (!response || !response.candidates || response.candidates.length === 0) {
            throw new Error('No image generated by Gemini API');
        }

        const candidate = response.candidates[0];

        // Extract image data from the response
        // Note: Gemini 2.5 Flash Image returns image data in the response
        let imageData = null;

        if (candidate.content && candidate.content.parts) {
            for (const part of candidate.content.parts) {
                if (part.inlineData && part.inlineData.mimeType && part.inlineData.mimeType.startsWith('image/')) {
                    imageData = part.inlineData.data;
                    break;
                }
            }
        }

        if (!imageData) {
            throw new Error('No image data found in Gemini API response');
        }

        // Convert base64 to buffer
        const imageBuffer = Buffer.from(imageData, 'base64');

        console.log(`✅ Image generated successfully (${imageBuffer.length} bytes)`);

        return imageBuffer;

    } catch (error) {
        console.error('Gemini API Error:', error.message);

        if (error.message.includes('API key')) {
            throw new Error('Invalid or missing Gemini API key. Please check your GEMINI_API_KEY environment variable.');
        } else if (error.message.includes('quota')) {
            throw new Error('Gemini API quota exceeded. Please check your usage limits.');
        } else if (error.message.includes('timeout')) {
            throw new Error('Gemini API request timed out. Please try again.');
        } else {
            throw new Error(`Gemini API error: ${error.message}`);
        }
    }
};

module.exports = {
    generateImageWithBnana
};
